import { grenadierData } from './enemies/grenadier';
import { guardHoundData } from './enemies/guardHound';
import { monodriveData } from './enemies/monodrive';
import { riotTrooperData } from './enemies/riotTrooper';
import { scorpionSentinelData } from './enemies/scorpionSentinel';
import { securityOfficerData } from './enemies/securityOfficer';
import { sentryRayData } from './enemies/sentryRay';
import { shockTrooperData } from './enemies/shockTrooper';
import { sweeperData } from './enemies/sweeper';
import { theHuntsmanData } from './enemies/theHuntsman';

export const enemiesGrenadierData = grenadierData;
export const enemiesGuardHoundData = guardHoundData;
export const enemiesMonodriveData = monodriveData;
export const enemiesRiotTrooperData = riotTrooperData;
export const enemiesScorpionSentinelData = scorpionSentinelData;
export const enemiesSecurityOfficerData = securityOfficerData;
export const enemiesSentryRayData = sentryRayData;
export const enemiesShockTrooperData = shockTrooperData;
export const enemiesSweeperData = sweeperData;
export const enemiesTheHuntsmanData = theHuntsmanData;
