import {
    enemiesCeruleanDrakeData,
    enemiesDoomratData,
    enemiesEliteSecurityOfficerData,
    enemiesGorgerrData,
    enemiesGrenadierData,
    enemiesGuardHoundData,
    enemiesHoodlumData,
    enemiesLesserDrakeData,
    enemiesMonodriveData,
    enemiesRiotTrooperData,
    enemiesScorpionSentinelData,
    enemiesSecurityOfficerData,
    enemiesSentryRayData,
    enemiesShockTrooperData,
    enemiesSweeperData,
    enemiesTheHuntsmanData,
    enemiesWereratData,
    enemiesWrathHoundData,
} from './api/mod';

export const Data = {
    enemiesCeruleanDrakeData,
    enemiesDoomratData,
    enemiesEliteSecurityOfficerData,
    enemiesGorgerrData,
    enemiesGrenadierData,
    enemiesGuardHoundData,
    enemiesHoodlumData,
    enemiesLesserDrakeData,
    enemiesMonodriveData,
    enemiesRiotTrooperData,
    enemiesScorpionSentinelData,
    enemiesSecurityOfficerData,
    enemiesSentryRayData,
    enemiesShockTrooperData,
    enemiesSweeperData,
    enemiesTheHuntsmanData,
    enemiesWereratData,
    enemiesWrathHoundData,
};
